In [1]:
import bempp.api
from bempp.api.linalg.iterative_solvers import gmres
bempp.api.set_ipython_notebook_viewer()
import numpy as np

def smallest_eigenvalue(A):
    #A=np.linalg.inv(A);
    print(A)
    v=5*np.random.rand(np.shape(A)[0],1);
    dif=1;
    w=1;
    v=v/np.linalg.norm(v)
    e=0.0001;                  
    
    while(dif>=e):
        x=np.linalg.solve(A,v)
        w=np.linalg.norm(x)
        if(w!=0):
            x=x/w
        else:
            return 0;
        dif=np.linalg.norm(x-v) 
        #print(v,x,"\n")
        v=x
    
    return 1/w
    
M=np.matrix([[3,2,0],[0,1,1],[0,1,2]]); #test matrica
M_rand=10*np.random.random((3,3));


print("\n",smallest_eigenvalue(M))
print("\n",np.linalg.eigvals(M))
#print("\n",smallest_eigenvalue(M_rand))
print(np.linalg.eigvals(M_rand))

[[3 2 0]
 [0 1 1]
 [0 1 2]]

 0.381964141129

 [ 3.          0.38196601  2.61803399]
[ -5.25033998  14.04266078   4.24185302]
